### PR TITLE
Add get_or_404()

### LINKED ISSUE #88: get_or_404 místo ručního abortu v detail
Viz https://github.com/frenzymadness/donors_registry/pull/69#discussion_r627352873.

Pokračování #69.

### PR DESCRIPTION
**Pull request by nappex**
Fix #88

### CODE REVIEW

**Comment by nappex** [comment]
I am little bit confused by part of code where we `None` return value we've been already handling

See for example registry/donors/views.py:

```python
medal = Medals.query.get(request.form["medal_id"])

if medal is None:
    flash("Odeslána nevalidní data.", "danger")
    return redirect(url_for("donor.overview"))

for rodne_cislo in request.form.getlist("rodne_cislo"):
    do = DonorsOverview.query.get(rodne_cislo)
    if do is None:
        flash("Odeslána nevalidní data.", "danger")
        return redirect(url_for("donor.award_prep", medal_slug=medal.slug))
```

Do we want to rewrite logic of `flash` to` 404.html` ?  I  don't think so.

**Comment by frenzymadness** [comment]
The flash messages in the mentioned function are there for a potential hacker because the function takes its inputs from HTTP POST from a form generated by another view and therefore should never be invalid.

I'd use `get_or_404` in the views where we take information from URL parameters that a user can simply manipulate.

Here is the list of potential candidates:
```
$ flask routes | grep "GET" | grep -Ev "debug|static" | grep "<"
donor.award_prep               GET        /award_prep/<medal_slug>
donor.batch_detail             GET        /batch_detail/<id>
donor.detail                   GET        /detail/<rc>
```

**Comment by frenzymadness** [comment]
And I'd create one common test for the 404 pages like the one we have for 401: https://github.com/frenzymadness/donors_registry/blob/db5697da796886a9c9e6d3abbebe20189d3c379e/tests/test_functional.py#L38

**Review by frenzymadness — APPROVED** [review]

**Review by Glutexo — COMMENTED** [review]
Chybí testy pro 404 medaile a dávky.

**Review by Glutexo — COMMENTED** [review]
Ověřen stávající automatický test. Ručně ověřeny všechny tři případy. :shipit:

**Pull request merged**
